// TypeScript types for EPIC 9: Daily AI Summary
// Covers the shape of aggregated daily data and database row formats.

/**
 * The full daily summary record stored in the daily_summaries table.
 */
export interface DailySummary {
    id: string
    summaryDate: string           // ISO date string: 'YYYY-MM-DD'
    totalPatients: number
    avgStageTimeMinutes: number
    delayCount: number
    avgTatMinutes: number
    totalBedsUsed: number
    totalStageUpdates: number
    generatedAt: string           // ISO timestamp
    aiSummary?: string            // Human-readable summary text generated by AI
    metadata: DailySummaryMetadata
}

/**
 * Flexible extra fields stored in the JSONB metadata column.
 * Extend this as more data points are needed by the AI layer.
 */
export interface DailySummaryMetadata {
    mostDelayedStage?: string     // Stage name with highest delay count
    // Future fields (add here when computed):
    // busiestHour?: number       // 0-23 hour with most activity
    // peakBedCount?: number      // Max concurrent occupied beds
}

/**
 * Raw aggregation result computed from the database before writing.
 * Mirrors DailySummary but without id/generatedAt (those are DB-assigned).
 */
export interface DailySummaryInput {
    summaryDate: string
    totalPatients: number
    avgStageTimeMinutes: number
    delayCount: number
    avgTatMinutes: number
    totalBedsUsed: number
    totalStageUpdates: number
    aiSummary?: string
    metadata: DailySummaryMetadata
}

/**
 * Result returned from a generate/aggregate operation.
 */
export interface AggregationResult {
    success: boolean
    date: string
    summary?: DailySummary
    error?: string
}
