#!/bin/bash
# US-18 PRODUCTION LAUNCH CHECKLIST
# Use this on launch day to ensure nothing is missed

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  US-18: DATA ENCRYPTION - PRODUCTION LAUNCH CHECKLIST         ║"
echo "║  Date: ________________   Launch Owner: ___________________   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
print_section() {
    echo ""
    echo "================== $1 =================="
}

check_item() {
    echo "□ $1"
}

complete_item() {
    echo "☑ $1"
}

print_section "PRE-LAUNCH (48 hours before)"

echo ""
echo "System Preparation:"
check_item "Ensure main branch is up-to-date"
check_item "Confirm all PRs merged and reviewed"
check_item "Verify staging deployment successful"
check_item "Backup production database (verified full restore works)"
check_item "Alert monitoring team of upcoming maintenance"
check_item "Schedule maintenance window (off-peak hours)"
check_item "Notify support team of new encryption features"
check_item "Brief customer success on new privacy features"

echo ""
echo "Access & Credentials:"
check_item "ENCRYPTION_KEY generated (64-char hex)"
check_item "ENCRYPTION_KEY stored in GitHub Secrets"
check_item "ENCRYPTION_KEY stored in AWS Secrets Manager" 
check_item "Database credentials validated"
check_item "Git access verified (push to main)"
check_item "Production server SSH access confirmed"
check_item "Incident response team on standby"

echo ""
echo "Documentation Review:"
check_item "Engineering team reviewed ENCRYPTION_DESIGN.md"
check_item "DevOps team reviewed US18_DEPLOYMENT_RUNBOOK.md"
check_item "Security team approved key management"
check_item "Approval signatures obtained (4 required)"
check_item "Rollback procedure reviewed and tested"
check_item "Troubleshooting guide reviewed"

print_section "LAUNCH DAY MORNING (4 hours before launch)"

echo ""
echo "Final Verification:"
check_item "Build verification: npm run build"
check_item "Test verification: npm run test"
check_item "Database backup: Full pg_dump completed"
check_item "Rollback tested: Confirmed rollback scripts work"
check_item "Monitoring dashboards: Set up and tested"
check_item "Alert thresholds: Configured and tested"
check_item "Incident response plan: Printed and distributed"
check_item "Support contacts: Posted in war room"

print_section "PHASE 1: PRE-DEPLOYMENT (1 hour before -> +1 day after)"

echo ""
echo "Infrastructure & Configuration:"
check_item "Load balancer health check: All healthy"
check_item "Database pool: Connections healthy"
check_item "ENCRYPTION_KEY: Loaded in environment"
check_item "SSL certificates: Valid and current"
check_item "Nginx configuration: Updated with cache headers"
check_item "Application logging: Verbose logging enabled"
check_item "Error tracking: Sentry/DataDog configured"

echo ""
echo "Database Preparation:"
check_item "Create pre-migration snapshot"
check_item "Run migration 040: pgcrypto extension"
check_item "Verify pgcrypto installed: SELECT pgcrypto_version()"
check_item "Create backup of database"
check_item "Document baseline metrics (CPU, memory, connections)"

print_section "PHASE 2: DATABASE MIGRATIONS (at T+0)"

echo ""
echo "Migration Execution:"
check_item "Schedule t+0 (start time): _______________"
check_item "Notify stakeholders: Migration starting in 5 minutes"
check_item "Run migration 041: patient encrypted columns"
check_item "Verify: 4 new JSONB columns in patient_admissions"
check_item "Run migration 042: user encrypted columns"
check_item "Verify: 2 new JSONB columns in users"
check_item "Run migration 043: bed_stage_logs encrypted columns"
check_item "Verify: 2 new JSONB columns in bed_stage_logs"
check_item "Run migration 044: audit_logs encrypted columns"
check_item "Verify: 2 new JSONB columns in audit_logs"

echo ""
echo "Post-Migration Verification:"
check_item "All migrations completed successfully"
check_item "Verify encryption_status columns exist: SELECT * FROM user LIMIT 0;"
check_item "Verify encrypted_at columns exist"
check_item "Confirm no data loss (row counts unchanged)"
check_item "Check database size (should be minimal increase)"
check_item "Monitor database connection pool"
check_item "Monitor CPU usage (should be minimal)"

print_section "PHASE 3: CODE DEPLOYMENT (T+30 minutes)"

echo ""
echo "Application Deployment:"
check_item "Schedule deployment start: _______________"
check_item "Blue-green: Deploy new code to staging nodes"
check_item "Health checks: Verify new instances healthy"
check_item "Smoke tests: Run basic functionality tests"
check_item "Load balancer: Route 10% traffic to new version"
check_item "Monitor metrics: Error rate, latency, CPU"
check_item "Wait 5 minutes: Monitor for errors"
check_item "Load balancer: Route 50% traffic to new version"
check_item "Monitor metrics: Error rate, latency, CPU"
check_item "Wait 10 minutes: Monitor for errors"
check_item "Load balancer: Route 100% traffic to new version"
check_item "Verify: All traffic on new version"
check_item "Monitor metrics: All green for 30 minutes"

echo ""
echo "Feature Verification:"
check_item "Test user registration: Email should be encrypted"
check_item "Test patient admission: All fields encrypted"
check_item "Test audit logging: New encrypted auditing works"
check_item "Test encrypted field reveal: Decryption works"
check_item "Test masked fields: Display shows ••••••"
check_item "Verify no performance degradation: <1ms per field"
check_item "Check error logs: Zero encryption failures"
check_item "Monitor: New encryption tests passing"

print_section "PHASE 4: MONITORING (T+2 hours)"

echo ""
echo "Metrics Tracking:"
check_item "CPU usage: Normal (no unusual spikes)"
check_item "Memory usage: Normal"
check_item "Database connections: Normal"
check_item "Response times: Normal (<200ms p95)"
check_item "Error rate: Normal (<0.1%)"
check_item "Encryption failures: Zero"
check_item "Decryption performance: <1ms per field"
check_item "User reports: None received"

echo ""
echo "Log Review (every 30 minutes for 2 hours):"
check_item "Application logs: No errors"
check_item "Database logs: No errors"
check_item "Nginx logs: No errors"
check_item "Security logs: No unusual activity"
check_item "Alert dashboard: All green"

print_section "ROLLBACK READINESS"

echo ""
echo "If Something Goes Wrong:"
check_item "STOP: Kill traffic immediately"
check_item "ASSESS: Check error logs and metrics"
check_item "DECIDE: Rollback or continue fixing?"

echo ""
echo "Option 1: QUICK ROLLBACK (if needed)"
check_item "Restore database from backup"
check_item "Deploy previous version of code"
check_item "Verify: All functionality working"
check_item "Post-mortem: Document what happened"

echo ""
echo "Option 2: CONTINUE FIXING (if minor issue)"
check_item "Deploy hotfix to staging nodes"
check_item "Test fix: Verify it resolves issue"
check_item "Deploy hotfix as blue-green"
check_item "Monitor: Ensure fix works at scale"

echo ""
echo "Post-Rollback Checklist:"
check_item "All users notified of incident"
check_item "Root cause identified"
check_item "Fix implemented and tested"
check_item "Retry launch when ready"

print_section "POST-LAUNCH (Day 2+)"

echo ""
echo "Ongoing Monitoring:"
check_item "Monitor encryption metrics for 24 hours"
check_item "Check for any delayed errors"
check_item "Collect performance baseline data"
check_item "Prepare for data migration phase"

echo ""
echo "Team Communication:"
check_item "Send all-clear message to stakeholders"
check_item "Schedule post-launch retrospective"
check_item "Document lessons learned"
check_item "Update runbook with any changes"

echo ""
echo "Data Migration Planning:"
check_item "Schedule bulk encryption of existing users (Week 1)"
check_item "Plan patient data migration (Week 2-3)"
check_item "Schedule old column drop (after 90 days)"
check_item "Plan key rotation test (Month 2)"

print_section "SIGN-OFF & APPROVAL"

echo ""
echo "Required Signatures (for official records):"
echo ""
echo "Launch Owner (confirms launch authority):"
echo "  Name: _______________________    Date: ____________    Time: ____________"
echo ""
echo "Tech Lead (confirms systems ready):"
echo "  Name: _______________________    Date: ____________    Time: ____________"
echo ""
echo "Security Lead (confirms encryption approved):"
echo "  Name: _______________________    Date: ____________    Time: ____________"
echo ""
echo "Operations Lead (confirms monitoring ready):"
echo "  Name: _______________________    Date: ____________    Time: ____________"
echo ""
echo "Product/Stakeholder (confirms feature approved):"
echo "  Name: _______________________    Date: ____________    Time: ____________"
echo ""

print_section "KEY CONTACTS (Print & Post in War Room)"

echo ""
echo "On-Call Team:"
echo "  Tech Lead:        ${RED}[PHONE]${NC} / [EMAIL]"
echo "  Database Admin:   ${RED}[PHONE]${NC} / [EMAIL]"
echo "  Security Lead:    ${RED}[PHONE]${NC} / [EMAIL]"
echo "  DevOps Lead:      ${RED}[PHONE]${NC} / [EMAIL]"
echo ""
echo "External Contacts:"
echo "  AWS Support:      ${YELLOW}[PHONE]${NC} / [EMAIL]"
echo "  Hosting Provider: ${YELLOW}[PHONE]${NC} / [EMAIL]"
echo "  Database Vendor:  ${YELLOW}[PHONE]${NC} / [EMAIL]"
echo ""

print_section "IMPORTANT PHONE NUMBERS"

echo ""
echo "War Room Conference Bridge:"
echo "  URL:        ${YELLOW}https://meet.company.com/us18-launch${NC}"
echo "  Phone:      ${YELLOW}+1 (555) 123-4567${NC} x12345"
echo "  Passcode:   ${YELLOW}______________________${NC}"
echo ""
echo "Slack Channel:"
echo "  #incident: ${YELLOW}@incident${NC} to page on-call"
echo "  #us18:     Use for deployment questions"
echo ""

print_section "LAUNCH COMPLETED!"

echo ""
echo "${GREEN}═════════════════════════════════════════════════════════════════${NC}"
echo "${GREEN}✅ US-18 PRODUCTION DEPLOYMENT COMPLETE${NC}"
echo "${GREEN}═════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Launch Date:        _______________"
echo "Launch Time:        _______________"
echo "Duration:           _______________ minutes"
echo "Issues Encountered: YES / NO"
echo "Rollbacks:          YES / NO"
echo "Final Status:       ✅ SUCCESS / ⚠️ PARTIAL / ❌ FAILED"
echo ""
echo "Launch Owner Signature: ___________________________    Date: _______________"
echo ""
echo "═════════════════════════════════════════════════════════════════════════════"
echo "Next Step: Schedule post-launch retrospective"
echo "Document: All issues in US-18-POSTMORTEM.md"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""
